# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f39869d05fff22eba61be51dbbe4d56b1a65851d395eedf845f597f4e4ac0dcea7982426d0860893e89e511241b3de048154286d0a7822df858baceada2a8b1

test:
  secret_key_base: 80ed2b77e41ceeacc19ff9522a849dddaa4093af51a879767141635cd0bcb961e5fe28b915bc4232ebeab37b1377372c3409da658bcde30b8c32df4bebb21908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
